.gitignore
In this pull request, I update the .gitignore file to overlook JetBrain IDE changes in the repo.
=> Updated .gitignore for JetBrains IDEs

 embedded_ml_exercise.qmd, embedded_sys_exercise.qmd
New Exercises 2 and 4 .qmd files. (2 should be OK, but 4 has an issue to preview HTML)
=> Exercises 2 and 4

.github/workflows/build_pages.yml, .github/workflows/deploy_page.yml
Closes #38 
Closes #39 
1. **Content**
=> Add Github actions

community.qmd
=> Added link to the tinymledu webpage

ai_for_good.qmd, references.bib
1. **Content**
- [ x] The chapter content is complete and covers the topic in detail.
- [ x] All technical terms are well-defined and explained.
- [ NA] Any code snippets or algorithms are well-documented and tested.
- [ x] The chapter follows a logical flow and structure.
- [ x] All references are correctly listed at the end of the chapter.
- [x ] In-text citations are used appropriately and match the references.
- [ NA] All figures, tables, and images have proper sources and are cited correctly.
- [ x] The chapter has been locally built and tested using Quarto.
- [x ] All images, figures, and tables …
=> Added a medical example in AI for Good chapter

ondevice_learning.qmd
=> Fix typo (ondevice -> on-device)

CODE_OF_CONDUCT.md
- Fixed email address in the code of conduct.
=> fix the email addresses

contents/efficient_ai/efficient_ai.bib, contents/efficient_ai/efficient_ai.qmd
=> Add references to ResNet-SE and ResNeXt papers

_quarto.yml
- Add version to Google Analytics
=> add version to ga

contents/benchmarking/benchmarking.qmd, contents/sustainable_ai/sustainable_ai.bib, contents/sustainable_ai/sustainable_ai.qmd
This PR does two things:
- Add existing efforts for ML energy measurement and optimization
- Add a piece of information regarding data gaps in the LCA section
CC @profvjreddi 
Closes #143. 
---
1. **Content**
=> Additions for Chapter 17 Sustainable AI

contents/niclav_sys/niclav_sys.qmd
=> Typo fixed in _Installing the OpenMV IDE_ chapter

_quarto.yml, contents/niclav_sys/niclav_sys.qmd
1. Change path _quarto.yml:
- /Users/VJ/Documents/GitHub/cs249r_book/custom_callout.lua to
- custom_callout.lua
2. Change the code link on niclav_sys/nicalv_sys.qmd
1. **Content**
- [ x] The chapter content is complete and covers the topic in detail.
- [x ] The chapter has been locally built and tested using Quarto.
- [x ] All external links (if any) are working and lead to the intended destinations.
- [x ] The chapter is pushed to the correct branch on the repository.
- [ x] The Pull Request is made with a clear title …
=> Correct links

contents/data_engineering/data_engineering.qmd, contents/efficient_ai/efficient_ai.qmd, contents/embedded_sys/embedded_sys.qmd, contents/ondevice_learning/ondevice_learning.qmd, contents/optimizations/optimizations.qmd
=> added more slides

contents/ai_for_good/ai_for_good.qmd, contents/benchmarking/benchmarking.qmd, contents/data_engineering/data_engineering.qmd, contents/dl_primer/dl_primer.qmd, contents/embedded_ml/embedded_ml.qmd, contents/frameworks/frameworks.qmd, contents/hw_acceleration/hw_acceleration.qmd, contents/ondevice_learning/ondevice_learning.qmd, contents/ops/ops.qmd, contents/optimizations/optimizations.qmd, contents/privacy_security/privacy_security.qmd, contents/sustainable_ai/sustainable_ai.qmd, contents/training/training.qmd
=> adding more colabs

contents/dl_primer/dl_primer.qmd, contents/ondevice_learning/ondevice_learning.qmd, contents/ops/ops.qmd, contents/optimizations/optimizations.qmd, contents/training/training.qmd
=> added videos to chapters

contents/ai_for_good/ai_for_good.qmd, contents/dl_primer/dl_primer.qmd, contents/hw_acceleration/hw_acceleration.qmd, contents/ondevice_learning/ondevice_learning.qmd, contents/ops/ops.qmd, contents/optimizations/optimizations.qmd, contents/privacy_security/privacy_security.qmd, contents/responsible_ai/responsible_ai.qmd, contents/training/training.qmd
=> added short captions for the videos

contents/robust_ai/robust_ai.bib, contents/robust_ai/robust_ai.qmd
=> Incorporating feedback from Yanjing

contents/learning_resources.qmd, contents/tools.qmd
=> Add XIAO ESP32S3 Sense in hardware list and add a book about XIAO in book list.

contents/robust_ai/robust_ai.bib, contents/robust_ai/robust_ai.qmd
Sercan Aygun: I added a paragraph about BNNs in the Transient Faults Section.
1. **Content**
=> iss2-adding-BNN-info

_quarto.yml
https://github.com/harvard-edge/cs249r_book/issues/76
=> 76 Break chapters into subfiles

_quarto.yml, contents/ai_for_good/ai_for_good.qmd, contents/benchmarking/benchmarking.qmd, contents/data_engineering/data_engineering.qmd, contents/dl_primer/dl_primer.qmd, contents/efficient_ai/efficient_ai.qmd, contents/frameworks/frameworks.qmd, contents/hw_acceleration/hw_acceleration.qmd, contents/ml_systems/ml_systems.qmd, contents/ondevice_learning/ondevice_learning.qmd, contents/ops/ops.qmd, contents/optimizations/optimizations.qmd, contents/privacy_security/privacy_security.qmd, contents/responsible_ai/responsible_ai.qmd, contents/robust_ai/robust_ai.qmd, contents/sustainable_ai/sustainable_ai.qmd, contents/training/training.qmd, contents/workflow/workflow.qmd
https://github.com/harvard-edge/cs249r_book/issues/253
=> 253 Videos need cross-references

contents/hw_acceleration/hw_acceleration.qmd
https://github.com/harvard-edge/cs249r_book/issues/279
=> 279 citation missing

_quarto.yml, contents/labs/arduino/nicla_vision/nicla_vision.qmd, contents/labs/getting_started.qmd, contents/labs/labs.qmd, contents/labs/seeed/xiao_esp32s3/xiao_esp32s3.qmd
Edits to the benchmarking chapter with a focus on brevity and cleaner language/flow.
This commit only covers up to and including the system benchmarking section. Future commits will cover the rest.
1. **Content**
=> 282 create overview section for labs

contents/dl_primer/dl_primer.qmd
=> Fixed video 3.1 link

contents/ai_for_good/ai_for_good.qmd, contents/benchmarking/benchmarking.qmd, contents/data_engineering/data_engineering.qmd, contents/dl_primer/dl_primer.qmd, contents/efficient_ai/efficient_ai.qmd, contents/frameworks/frameworks.qmd, contents/hw_acceleration/hw_acceleration.qmd, contents/labs/arduino/nicla_vision/nicla_vision.qmd, contents/labs/seeed/xiao_esp32s3/xiao_esp32s3.qmd, contents/ml_systems/ml_systems.qmd, contents/ondevice_learning/ondevice_learning.qmd, contents/ops/ops.qmd, contents/optimizations/optimizations.qmd, contents/privacy_security/privacy_security.qmd, contents/responsible_ai/responsible_ai.qmd, contents/robust_ai/robust_ai.qmd, contents/sustainable_ai/sustainable_ai.qmd, contents/training/training.qmd
Made the formatting consistent
=> Updated Credit -> Source: and fixed formatting style to be consistent

contents/ai_for_good/ai_for_good.qmd, contents/dl_primer/dl_primer.qmd, contents/hw_acceleration/hw_acceleration.qmd, contents/labs/arduino/nicla_vision/kws/kws.qmd, contents/ondevice_learning/ondevice_learning.qmd, contents/ops/ops.qmd, contents/privacy_security/privacy_security.qmd, contents/responsible_ai/responsible_ai.qmd, contents/training/training.qmd
https://github.com/harvard-edge/cs249r_book/issues/326
=> 326 PDF video links are broken

_quarto.yml, style.scss
https://github.com/harvard-edge/cs249r_book/issues/331
=> 331 Marginnotes needs to be left aligned, but they seem to be justified 

contents/frameworks/frameworks.qmd, contribute.md
https://github.com/harvard-edge/cs249r_book/issues/346
=> 346 2 typos in frameworks.qmd

contents/data_engineering/data_engineering.qmd
Thanks to @BravoBaldo for finding these issues.
=> 358 Typos in "data_engineering.qmd"

contents/zoo_datasets.qmd
=> Add Wake Vision to zoo_datasets.qmd

contents/optimizations/optimizations.qmd
https://github.com/harvard-edge/cs249r_book/issues/369
=> 369 Missing format ...maybe

_quarto.yml, tex/header-includes.tex
https://github.com/harvard-edge/cs249r_book/issues/372
=> 372 Slowdown after changing "header-includes.tex"

contents/frameworks/frameworks.qmd, contents/hw_acceleration/hw_acceleration.qmd, contents/privacy_security/privacy_security.qmd, contents/sustainable_ai/sustainable_ai.qmd
https://github.com/harvard-edge/cs249r_book/issues/385
=> 385 Bad link in hw_acceleration.qmd / Section 10.6

contents/benchmarking/benchmarking.qmd
https://github.com/harvard-edge/cs249r_book/issues/402
=> 402 Note on first 4 chapter of "benchmarking.qmd"

contents/ops/ops.qmd
https://github.com/harvard-edge/cs249r_book/issues/419
=> 419 Notes on the first part of "ops.qmd"

contents/privacy_security/privacy_security.qmd
https://github.com/harvard-edge/cs249r_book/issues/431
=> 431 Notes in "privacy_security.qmd"

contents/sustainable_ai/sustainable_ai.qmd
https://github.com/harvard-edge/cs249r_book/issues/438
=> 438 Points to review in "sustainable_ai.qmd"

contents/ai_for_good/ai_for_good.qmd
https://github.com/harvard-edge/cs249r_book/issues/445
=> 445 Notes in "ai_for_good.qmd"

contents/conclusion/conclusion.qmd, contents/ops/ops.qmd
https://github.com/harvard-edge/cs249r_book/issues/447
=> 447 In "conclusion.qmd"

contents/privacy_security/privacy_security.qmd
=> privacy security changes- add few lines

contents/labs/raspi/object_detection/object_detection.qmd
https://github.com/harvard-edge/cs249r_book/issues/485
=> 485 Only 2 notes

contents/core/benchmarking/benchmarking.qmd, contents/core/ops/ops.qmd
https://github.com/harvard-edge/cs249r_book/issues/498
=> 498 Some new issues

contents/about.qmd
https://github.com/harvard-edge/cs249r_book/issues/501
=> 501 One section is mistakenly bold

_quarto.yml, contents/labs/overview.qmd, contents/main.qmd
https://github.com/harvard-edge/cs249r_book/issues/488
=> 488 Problems about "Parts"

tex/header-includes.tex
https://github.com/harvard-edge/cs249r_book/issues/506
=> 506 TOC spacing is messed up -- too close to titles when section numbers are big in count

contents/core/introduction/introduction.qmd
https://github.com/harvard-edge/cs249r_book/issues/510
=> 510 Create a reading guide for learners

README.md
=> README updated with quarto rendering to EPUB

README.md
- [ X ] The text has been proofread for grammar and spelling errors.
- [ X ] All images, figures, and tables render properly without any glitches.
- [ X ] All images have a source or they are properly linked to external sites. 
- [ X ] The chapter's formatting is consistent with the rest of the book.
- [ X ] The chapter has been locally built and tested using Quarto.
=> Add badge labels

contents/core/ml_systems/ml_systems.qmd
https://github.com/harvard-edge/cs249r_book/issues/555
=> 555 Figure 2.7 is not rendered correctly (dev version only)

_quarto.yml, contents/frontmatter/about/about.qmd, index.qmd
https://github.com/harvard-edge/cs249r_book/issues/572
=> 572 Bad link in \cs249r_book\index.qmd and others

contents/core/introduction/introduction.qmd
https://github.com/harvard-edge/cs249r_book/issues/589
=> 589 Chapter 1, PDF format

contents/core/workflow/workflow.qmd
https://github.com/harvard-edge/cs249r_book/issues/599
=> 599 Feedback on Chapter 5: AI Workflow

contents/core/dnn_architectures/dnn_architectures.qmd
https://github.com/harvard-edge/cs249r_book/issues/620
=> 620 Typos "×" in dnn_architectures

contents/labs/raspi/object_detection/object_detection.qmd
Updated file object_detection.qmd
=> Issue #632

contents/core/data_engineering/data_engineering.qmd
=> initial new content (wip)

_quarto.yml
"Introduction to" was added to the cover
=> Update Cover page

_quarto.yml, contents/appendix/phd_survival_guide.qmd, contents/core/training/training.qmd, tex/header-includes.tex
https://github.com/harvard-edge/cs249r_book/issues/652
=> 652 Create "Resources" placeholder

scripts/clean_bibtex.sh
https://github.com/harvard-edge/cs249r_book/issues/651
=> 651 Write a script to find duplicate definitions

.github/workflows/quarto-build.yml, Machine-Learning-Systems.log, contents/core/workflow/workflow.qmd, tex/header-includes.tex
=> Updated ch5: workflow.qmd

_quarto.yml, contents/core/frameworks/frameworks.qmd
Figures 7.3, 7.4, 7.5, 7.6, 7.7, 7.9, 7.10 and 7.11 have been updated. 
The _quarto.yml file has been updated with newly defined colors for the diagram boxes
=> Updated chapter 7: frameworks.qmd

CHANGELOG.md, contents/core/hw_acceleration/hw_acceleration.qmd
A new figure has been drawn (fig. 11.4).
=> Updated chapter 11

CHANGELOG.md, contents/core/hw_acceleration/hw_acceleration.qmd
=> Update ch11: hw_acceleration.qmd

contents/core/ml_systems/ml_systems.qmd
The fonts and colors on figures 2.10, 2.11, and 2.14 have been matched. 
The size of figures 2.12 and 2.13 has been adjusted so that they do not overlap their captions.
=> Update chapter 2:

contents/core/frameworks/frameworks.qmd
The fonts and colors on figure 7.3 has been matched. 
Figure 7.8 has been redrawn with Tikz package
Fixed correct appearance of figures starting from figure 7.11
=> Update chapter 7: frameworks.qmd

CHANGELOG.md, contents/core/workflow/workflow.qmd
The fonts and colors on figures 5.3, and 5.5  have been matched.
=> Update ch5: workflow

CHANGELOG.md, contents/core/introduction/introduction.qmd
The fonts and colors on figure 1.5 has been matched.
=> Update ch1: introduction.qmd

CHANGELOG.md, contents/core/dl_primer/dl_primer.qmd
Figure 3.14 has been redrawn with Tikz package
Figure 3.17 has been redrawn with Tikz package
The problem with the captions for Figures 3.14 and 3.15, which were displayed in the wrong places, has been fixed.
=> Update chapter 3: dl_primer

contents/core/efficient_ai/efficient_ai.qmd
https://github.com/harvard-edge/cs249r_book/issues/761
=> 761 Little typo in efficient_ai.qmd

.vale.ini, .vale/config.ini, .vale/styles/textbook/Capitalization.yml, .vale/styles/textbook/OxfordComma.yml, .vale/styles/textbook/Terminology.yml, .vale/styles/textbook/Vocabulary.yml
https://github.com/harvard-edge/cs249r_book/issues/767
=> 767 Setup vale formatting checks

contents/core/efficient_ai/efficient_ai.qmd
https://github.com/harvard-edge/cs249r_book/issues/764
=> 764 Some typos with "Source "

contents/core/data_engineering/data_engineering.qmd, contents/core/dnn_architectures/dnn_architectures.qmd, contents/core/ml_systems/ml_systems.qmd, style.scss, tex/header-includes.tex
https://github.com/harvard-edge/cs249r_book/issues/772
=> 772 Hypenation setup

contents/core/frameworks/frameworks.qmd, contents/labs/arduino/nicla_vision/image_classification/image_classification.qmd, contents/labs/arduino/nicla_vision/kws/kws.qmd, contents/labs/arduino/nicla_vision/motion_classification/motion_classification.qmd, contents/labs/seeed/xiao_esp32s3/image_classification/image_classification.qmd
https://github.com/harvard-edge/cs249r_book/issues/779
=> 779 A few notes

CHANGELOG.md, contents/labs/seeed/xiao_esp32s3/image_classification/image_classification.qmd, contents/labs/seeed/xiao_esp32s3/kws/kws.qmd, contents/labs/seeed/xiao_esp32s3/motion_classification/motion_classification.qmd, contents/labs/seeed/xiao_esp32s3/object_detection/object_detection.qmd, contents/labs/seeed/xiao_esp32s3/setup/setup.qmd, contents/labs/seeed/xiao_esp32s3/xiao_esp32s3.qmd, scripts/find_unreferenced_labels.py
The file xiao_esp32s3.qmd  has been edited.
The file setup.qmd  has been edited.
The file image_classification.qmd  has been edited. The file object_detetion.qmd  has been edited.
The file kws.qmd  has been edited.
The file motion_classification.qmd  has been edited.
=> Update LABS part 2_seeed_xiao_esp32s3

CHANGELOG.md, contents/core/dl_primer/dl_primer.qmd
Should the dimensions for $$W^L$$ be swapped in the [Mathematical Representation](https://mlsysbook.ai/contents/core/dl_primer/dl_primer.html#mathematical-representation) section? Since there are 10 neurons in the final output layer, then the dimensions of the final layer's weights in matrix form would be $$n_{L-1}$$ rows and 10 columns.
---
> - [ ] The chapter has been locally built and tested using Quarto.
Sorry, I didn't do this.
=> swap dimension order for W^L (in 

contents/labs/raspi/image_classification/image_classification.qmd, contents/labs/raspi/llm/llm.qmd, contents/labs/raspi/object_detection/object_detection.qmd, contents/labs/raspi/raspi.qmd, contents/labs/raspi/setup/setup.qmd, contents/labs/raspi/vlm/vlm.qmd, scripts/find_unreferenced_labels.py
=> 3labs raspi

.pre-commit-config.yaml, contents/labs/shared/dsp_spectral_features_block/dsp_spectral_features_block.qmd, contents/labs/shared/kws_feature_eng/kws_feature_eng.qmd, scripts/find_unreferenced_labels.py
=> 4labs shared

contents/core/introduction/introduction.qmd
In Figure 1.5, the rounded boxes have been removed and the colors have been matched to the defined colors
=> Updated chapter-1

contents/labs/arduino/nicla_vision/image_classification/image_classification.qmd, contents/labs/arduino/nicla_vision/setup/setup.qmd
https://github.com/harvard-edge/cs249r_book/issues/799
=> 799 Some notes in hw_acceleration.qmd

contents/core/data_engineering/data_engineering.qmd
Allows pull requests targeting the `main` or `dev` branches to trigger the controller workflow. This ensures that changes proposed in pull requests are validated by the workflow before merging.
=> PDF Build hangs on dataengineering.qmd 

contents/core/privacy_security/privacy_security.qmd
Labeling and referencing code blocks
Figure 15_3 has been redrawn with Tikz package
Figure 15_4 has been redrawn with Tikz package
Figure 15_6 has been redrawn with Tikz package
Figure 15_12 has been redrawn with Tikz package
Figure 15_14 has been redrawn with Tikz package
Figure 15_15 has been redrawn with Tikz package
Figure 15_17 has been redrawn with Tikz package
=> Updated chapter_15_privacy_security

contents/core/dl_primer/dl_primer.qmd
QR code has been added to video block.
=> Updated chapter_3_dl_primer

_extensions/custom-numbered-blocks/custom-numbered-blocks.lua
The counters for Question and Answer blocks have been fixed to match the numbering used in the PDF output.
=> Counters for callot blocks in html

_quarto.yml
Adjusted the chapter hierarchy in the _quarto.yml file to match the updated book structure.
=> Final test after syncing with upstream dev

book/contents/labs/raspi/vlm/vlm.qmd
- [x ] The text has been proofread for grammar and spelling errors.
- [x ] All images, figures, and tables render properly without any glitches.
- [x ] All images have a source or they are properly linked to external sites.
- [x ] The chapter's formatting is consistent with the rest of the book.
- [x ] The chapter has been locally built and tested using Quarto.
=> Update subtitles on vlm.qmd

quarto/contents/labs/ide_setup.qmd, quarto/contents/labs/kits.qmd, quarto/contents/labs/seeed/xiao_esp32s3/setup/setup.qmd
- [x ] The text has been proofread for grammar and spelling errors.
=> Xiaoml kit

quarto/contents/core/benchmarking/benchmarking.qmd
Figure 12.9 has been added to the chapter.
=> Add a new TikZ figure in chapter 12

config/tex/header-includes.tex, quarto/contents/core/efficient_ai/efficient_ai.qmd
Figure 9.5  has been added to the chapter.
The \providecommand was added before each \renewcommand to make the code more robust (header-includes.tex).
=> Add a new Tikz figure in chapter 9

quarto/contents/labs/seeed/xiao_esp32s3/image_classification/image_classification.qmd
_ESP32 by Espressif Systems_ is an Arduino Boards package, not a library.
=> Boards package - not library

quarto/contents/core/benchmarking/benchmarking.qmd, quarto/contents/core/dnn_architectures/dnn_architectures.qmd
Inserted new TikZ figures:
- chapter 4: fig. 4.12;
- chapter 12: fig. 12.3
=> New Tikz figures in chapters 4 & 12

quarto/contents/core/robust_ai/robust_ai.qmd
Figure #fig-three-pillars-framework (fig. 16.5) has been updated.
=> Update a Tikz figure in chapter-16
